/**
 * Stub file for type-checking purposes only.
 * This file mimics the payload-types.ts that will be generated by Payload.
 * It provides the basic types needed for type-checking the extras files.
 */

export interface User {
  id: string
  email: string
  name?: string | null
  betterAuthId?: string | null
  roles?: ('admin' | 'user')[] | null
  image?: string | null
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  createdAt: string
  updatedAt: string
}

export interface Page {
  id: string
  title: string
  slug?: string | null
  content?: any
  createdAt: string
  updatedAt: string
}

export interface Post {
  id: string
  title: string
  slug?: string | null
  content?: any
  author?: string | User | null
  createdAt: string
  updatedAt: string
}

export interface Category {
  id: string
  title: string
  slug?: string | null
  createdAt: string
  updatedAt: string
}

// Config types
export interface Config {
  collections: {
    users: User
    media: Media
    pages: Page
    posts: Post
    categories: Category
  }
  globals: {}
  locale: null
  user: User
}
